//! Golden tests against the original TypeScript implementation.
//!
//! The fixtures in `fixtures/` were generated by running the upstream Next.js
//! engine directly (see `docs/fixtures.md`). They pin every published rank:
//! if these pass, the Rust rewrite cannot move a single user's tier, division,
//! GP or percentile.
//!
//! Floats are compared for *exact* equality, not with an epsilon — serde_json
//! round-trips f64 losslessly, so drift here is a real difference in the
//! arithmetic and we want to see it. The one exception is `z_score`, where
//! V8's `Math.log` and Rust's `f64::ln` are separate libm implementations that
//! disagree in the last bit or two. That intermediate is never shown to a user,
//! and `elo` and `percentile` are both rounded well clear of the difference —
//! `rank_fields_that_users_see_are_bit_exact` proves the rounding never lands
//! on a boundary where it could matter.

use github_ranked_core::ranking::{
    AggregatedStats, Division, RankResult, Tier, calculate_elo, calculate_gp, calculate_percentile,
    calculate_rank, calculate_z_score, constants::seasonal_decay_multiplier, get_division,
    get_tier,
};
use serde::Deserialize;

fn fixture<T: serde::de::DeserializeOwned>(name: &str) -> T {
    let path = format!("{}/../../fixtures/{name}", env!("CARGO_MANIFEST_DIR"));
    let raw = std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("reading {path}: {e}"));
    serde_json::from_str(&raw).unwrap_or_else(|e| panic!("parsing {path}: {e}"))
}

/// Tolerance for the internal z-score, in ULPs.
///
/// The observed worst case against the upstream fixtures is 5 ULP (~2e-15
/// relative), entirely from `ln`. 8 leaves headroom for libm differences across
/// platforms while staying tight enough that a genuine algorithm change — which
/// would move the value by orders of magnitude more — still fails the test.
const MAX_Z_ULPS: u64 = 8;

/// Distance between two floats in representable steps (ULPs).
fn ulps_apart(a: f64, b: f64) -> u64 {
    if a == b {
        return 0;
    }
    let (a, b) = (a.to_bits() as i64, b.to_bits() as i64);
    a.abs_diff(b)
}

#[derive(Deserialize)]
struct RankCase {
    stats: AggregatedStats,
    expected: RankResult,
}

#[test]
fn calculate_rank_matches_upstream() {
    let cases: Vec<RankCase> = fixture("rank_cases.json");
    assert!(cases.len() > 3000, "fixture set looks truncated");

    let mut failures = Vec::new();
    let mut worst_z_ulps = 0u64;

    for (i, case) in cases.iter().enumerate() {
        let got = calculate_rank(&case.stats);
        let want = &case.expected;

        // Everything a user can see must be identical, bit for bit.
        let user_visible_matches = got.tier == want.tier
            && got.division == want.division
            && got.elo == want.elo
            && got.gp == want.gp
            && got.percentile == want.percentile
            && got.wpi == want.wpi;

        let z_ulps = ulps_apart(got.z_score, want.z_score);
        worst_z_ulps = worst_z_ulps.max(z_ulps);

        if !user_visible_matches || z_ulps > MAX_Z_ULPS {
            failures.push(format!(
                "case {i}: {:?}\n  expected {:?}\n  got      {:?}  (z-score off by {z_ulps} ulps)",
                case.stats, want, got
            ));
        }
    }

    assert!(
        failures.is_empty(),
        "{} of {} rank cases diverged:\n{}",
        failures.len(),
        cases.len(),
        failures
            .iter()
            .take(10)
            .cloned()
            .collect::<Vec<_>>()
            .join("\n")
    );

    eprintln!(
        "{} cases matched; worst z-score divergence: {worst_z_ulps} ulp(s)",
        cases.len()
    );
}

/// The z-score difference from libm could in principle push `elo` across an
/// integer boundary or `percentile` across a decimal one. Across the whole
/// fixture set it never does — this is what makes the port safe to ship.
#[test]
fn rank_fields_that_users_see_are_bit_exact() {
    let cases: Vec<RankCase> = fixture("rank_cases.json");

    let diverged = cases
        .iter()
        .filter(|c| {
            let got = calculate_rank(&c.stats);
            got.elo != c.expected.elo || got.percentile != c.expected.percentile
        })
        .count();

    assert_eq!(
        diverged, 0,
        "{diverged} cases had elo/percentile drift from libm"
    );
}

#[test]
fn every_tier_is_exercised() {
    let cases: Vec<RankCase> = fixture("rank_cases.json");
    for tier in Tier::ALL_DESC {
        assert!(
            cases.iter().any(|c| c.expected.tier == tier),
            "no fixture covers {tier}; the golden set has a blind spot"
        );
    }
}

/// Walks every integer Elo across the whole ladder, so all tier and division
/// boundaries are checked from both sides.
#[test]
fn tier_division_and_gp_match_upstream_at_every_elo() {
    let sweep: Vec<(f64, Tier, Option<Division>, f64)> = fixture("elo_sweep.json");
    assert_eq!(sweep.len(), 3401);

    for (elo, want_tier, want_division, want_gp) in sweep {
        let tier = get_tier(elo);
        assert_eq!(tier, want_tier, "tier at elo {elo}");

        let division = get_division(elo, tier);
        assert_eq!(division, want_division, "division at elo {elo}");

        let gp = calculate_gp(elo, tier, division);
        assert_eq!(gp, want_gp, "gp at elo {elo}");
    }
}

#[test]
fn percentile_and_elo_match_upstream_across_z_range() {
    let sweep: Vec<(f64, f64, f64)> = fixture("zscore_sweep.json");

    for (z, want_percentile, want_elo) in sweep {
        assert_eq!(
            calculate_percentile(z),
            want_percentile,
            "percentile at z={z}"
        );
        assert_eq!(calculate_elo(z), want_elo, "elo at z={z}");
    }
}

#[test]
fn z_score_matches_upstream_across_magnitudes() {
    let sweep: Vec<(f64, f64)> = fixture("wpi_sweep.json");

    let mut worst = 0u64;
    for (wpi, want) in sweep {
        let ulps = ulps_apart(calculate_z_score(wpi), want);
        assert!(
            ulps <= MAX_Z_ULPS,
            "z-score at wpi={wpi} off by {ulps} ulps"
        );
        worst = worst.max(ulps);
    }
    eprintln!("worst z-score divergence across magnitudes: {worst} ulp(s)");
}

#[test]
fn seasonal_decay_matches_upstream() {
    let sweep: Vec<(i32, i32, f64)> = fixture("decay_sweep.json");

    for (year, current_year, want) in sweep {
        assert_eq!(
            seasonal_decay_multiplier(year, current_year),
            want,
            "decay for year {year} in season {current_year}"
        );
    }
}

/// The star cap is a deliberate anti-farming rule, so pin it explicitly rather
/// than trusting it to fall out of the random fixtures.
#[test]
fn stars_stop_counting_at_the_cap() {
    let with = |stars: f64| {
        calculate_rank(&AggregatedStats {
            total_stars: stars,
            ..Default::default()
        })
    };

    assert_eq!(with(1_000.0), with(100_000.0));
    assert_ne!(with(999.0), with(1_000.0));
}
