[package]
name = "github-ranked-wasm"
description = "WebAssembly bindings for the ranking engine and card renderer."
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
github-ranked-core.workspace = true
serde.workspace = true
serde-wasm-bindgen = "0.6"
wasm-bindgen = "0.2"

[dev-dependencies]
wasm-bindgen-test = "0.3"
